version: "3.9"
services:
  backend:
    build: .
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8081:8080"
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: S754h19w?